### PR TITLE
Update WAF_Bypass_Using_headers.md

### PR DESCRIPTION
**Pull request by Mr-p0tat0**
Some headers that helps to bypaas firewall.

### CODE REVIEW

**Comment by KathanP19** [comment]
Please can you filter the file removing dupes and line by line

**Comment by Mr-p0tat0** [comment]
Proxy-Host: 127.0.0.1
Request-Uri: 127.0.0.1
X-Forwarded: 127.0.0.1
X-Forwarded-By: 127.0.0.1
X-Forwarded-For: 127.0.0.1
X-Forwarded-For-Original: 127.0.0.1
X-Forwarded-Host: 127.0.0.1
X-Forwarded-Server: 127.0.0.1
X-Forwarder-For: 127.0.0.1
X-Forward-For: 127.0.0.1
Base-Url: 127.0.0.1
Http-Url: 127.0.0.1
Proxy-Url: 127.0.0.1
Redirect: 127.0.0.1
Real-Ip: 127.0.0.1
Referer: 127.0.0.1
Referrer: 127.0.0.1
Refferer: 127.0.0.1
Uri: 127.0.0.1
Url: 127.0.0.1
X-Host: 127.0.0.1
X-Http-Destinationurl: 127.0.0.1
X-Http-Host-Override: 127.0.0.1
X-Original-Remote-Addr: 127.0.0.1
X-Original-Url: 127.0.0.1
X-Proxy-Url: 127.0.0.1
X-Rewrite-Url: 127.0.0.1
X-Real-Ip: 127.0.0.1
X-Remote-Addr: 127.0.0.1
X-Custom-IP-Authorization:127.0.0.1
X-Originating-IP: 127.0.0.1
X-Remote-IP: 127.0.0.1
X-Original-Url:
X-Forwarded-Server:
X-Host:
X-Forwarded-**Host**:
X-Rewrite-Url:

**Comment by KathanP19** [comment]
can you add some reference?

**Comment by Mr-p0tat0** [comment]
automated near about 2 month ago. I tried but didn't get real source. I use it for 403, ssrf, csrf, redirect. :-)

**Comment by KathanP19** [comment]
@all-contributors please add @Mr-p0tat0  for tutorial

**Comment by KathanP19** [comment]
thank you for contributing 👍

**Pull request merged**
