### PR TITLE
Create Web-Application-Pentesting-checklist.md

### PR DESCRIPTION
**Pull request by Harsha-Ambati**

### CODE REVIEW

**Comment by KathanP19** [comment]
was this made by you bro?

**Comment by Harsha-Ambati** [comment]
No bro!1 i have taken from varoius blogs and resources and compiled into MD file

**Comment by KathanP19** [comment]
Ok, great bro, If took from somewhere please add it in reference.

**Comment by KathanP19** [comment]
removing the previous small checklist.

**Comment by KathanP19** [comment]
bro its copy of this https://github.com/sehno/Bug-bounty/blob/master/bugbounty_checklist.md, please don't do this next time please give credits

**Comment by Harsha-Ambati** [comment]
bro I have added credits!! now merge it

**Pull request merged**
