### PR TITLE
Create SSRF-Dorks.md

### PR DESCRIPTION
**Pull request by SoftwareUser2three**

### CODE REVIEW

**Comment by KathanP19** [comment]
this is not the ssrf dorks just the params, please send dorks with proper formatting, and don't just copy-paste 💯

**Comment by SoftwareUser2three** [comment]
Ahh, sorry @KathanP19 actually i was adding dorks+params. sorry i was in hurry when i did let me change and add

**Comment by SoftwareUser2three** [comment]
Gonna update again

**Comment by KathanP19** [comment]
ok 👍

**Pull request closed without merging**
