### PR TITLE
Added GraphQL

### PR DESCRIPTION
**Pull request by rtcms**
Added GraphQL with some basic resources
Feel free to Add more :)

### CODE REVIEW

**Comment by KathanP19** [comment]
Hey sorry for the delay can i get your twitter handler?

**Comment by rtcms** [comment]
> Hey sorry for the delay can i get your twitter handler?

It's @0xrtt

**Comment by KathanP19** [comment]
Thanks for the contribution 👍

**Comment by KathanP19** [comment]
@all-contributors please add @rtcms  for tutorial

**Comment by rtcms** [comment]
Thanks for merging :)

**Pull request merged**
