### PR TITLE
Added Subdomain Takeover

### PR DESCRIPTION
**Pull request by SocioDroid**

### CODE REVIEW

**Comment by remonsec** [comment]
Hey 
You have explained awesome from beginning to end 
From the last couple of weeks, I am doing only Subdomain Takeover. I found that it requires proper and deep subdomain enumeration 

Can you please add all subdomain enumeration category so it may help more

> Passive
> Active
> Permutation

**Comment by SocioDroid** [comment]
That's a great idea!
Maybe we can add a Recon section and under that we can include the above topics!

**Comment by remonsec** [comment]
Awesome
@KathanP19 can you pull this out 
We will be sending more PR on Recon

Have a nice day @SocioDroid <3

**Comment by KathanP19** [comment]
Nice one bro, thank you for contributing

**Comment by KathanP19** [comment]
@all-contributors please add @SocioDroid for tutorial

**Pull request merged**
