### PR TITLE
Merge pull request #158 from KathanP19/all-contributors/add-th3d1p4k

### PR DESCRIPTION
**Pull request by dipakpanchal456**
docs: add th3.d1p4k as a contributor
CMS > Moodle

### CODE REVIEW

**Comment by dipakpanchal456** [comment]
https://dewangpanchal98.medium.com/mass-hunting-xss-moodle-ed4b50c82516
Writeup link.

**Comment by KathanP19** [comment]
Done Check CMS.

**Comment by KathanP19** [comment]
@all-contributors please add @dipakpanchal456  for tutorial

**Comment by dipakpanchal456** [comment]
Updated.
Thank you so much
Can you please change the author name from @dipakpanchal456 to @th3.d1p4k

**Pull request closed without merging**
