### PR TITLE
Web Penetration Testing Methodology Mindmap by Cristian Cornea

### PR DESCRIPTION
**Pull request by h4r5h1t-hrs**

### CODE REVIEW

**Comment by h4r5h1t-hrs** [comment]
Twitter: https://twitter.com/h4r5h1t_hrs

**Comment by KathanP19** [comment]
Thanks for the contribution and sorry for the delayed pull request.

**Comment by KathanP19** [comment]
@all-contributors please add @h4ckboy19  for tutorial

**Comment by KathanP19** [comment]
@all-contributors please add @h4r5h1t-hrs  for tutorial

**Pull request merged**
