### PR TITLE
File-upload-bypass

### PR DESCRIPTION
**Pull request by Harsha-Ambati**

### CODE REVIEW

**Comment by KathanP19** [comment]
is it completed or there is something left to add, it seems incomplete

**Comment by Harsha-Ambati** [comment]
will add some more in coming days...in part 2

**Comment by KathanP19** [comment]
should I merge this or wait

**Comment by Harsha-Ambati** [comment]
you can merge it!

**Comment by KathanP19** [comment]
thank you @Harsha-Ambati for contributing, 🥇

**Pull request merged**
