### PR TITLE
Create OTP_Bypass_by_repeating_requests.md

### PR DESCRIPTION
**Pull request by febinrev**
Bypassing OTP in registration forms by repeating the form submission multiple times using repeater

### CODE REVIEW

**Comment by KathanP19** [comment]
Please send your twitter handler.

**Comment by febinrev** [comment]
My twitter handle is : twitter.com/febinrev

**Comment by febinrev** [comment]
[twitter.com/febinrev](twitter.com/febinrev)

**Comment by KathanP19** [comment]
Thank you @febinrev for contribution 👍 , will be looking for more from you in the future.
@all-contributors please add @Yashrk078 for tutorial

**Comment by KathanP19** [comment]
@all-contributors please add @febinrev for tutorial

**Pull request merged**
