### PR TITLE
Broken_Authentication_To_Email_Verification_bypass

### PR DESCRIPTION
**Pull request by Raiders0786**
Hi There,

I have include a file of my finding in it :) Please review it & Do the needful .

### CODE REVIEW

**Comment by remonsec** [comment]
Hello
Thanks for your PR, we appreciate your effort
Have a sweet day

**Comment by Raiders0786** [comment]
Hey ,

thanks for merging :)

It's very nice to see that I contributed back after learning from it :)
Have learnt so many things from these before :)

**Comment by remonsec** [comment]
You are one of those who care about their people & community
Expecting more learning materials from you
This is how we grow <3

**Comment by Raiders0786** [comment]
Yes I believe In sharing and learning together,

Will share more in future   :)

I have messaged a doubt in twitter  , Please check it once :)

**Comment by KathanP19** [comment]
@all-contributors please add @Raiders0786  for tutorial

**Comment by KathanP19** [comment]
@all-contributors please add @Raiders0786 for tutorial

**Pull request merged**
